### ISSUE TITLE
Issue on page /10.envelope_maximum.html

### ISSUE THREAD

**Issue by Joshbob298** [fediskhakov/OptimCourse#10]
In the Maximum theorem under convexity, in the second scenario, 'the concavity of the function f(x, theta) with respect to x for each value of theta ...', it appears that the condition specifying the admissible set to be convex-valued has been omitted.

![image](https://github.com/fediskhakov/OptimCourse/assets/56542483/06b47427-c065-43a9-8cad-2d7d6df1b45e)

**Comment by fediskhakov** [comment]
This is correct, thank you! Lecture notes updated.
