### ISSUE TITLE
Minor bug - main TOC not fully updated

### ISSUE THREAD

**Issue by eilui** [fediskhakov/OptimCourse#2]
I noticed the left-hand TOC entry for Exercise Set C is currently only visible from 00.index and 04.basic_analysis (and from itself, 04.exercises) - nothing breaking, just looks a bit funny.  I don't have that much experience with building webpages, but I'm assuming it's something to do with the TOC only being updated for those pages which have been modified each time the site is built - see [this StackOverflow question](https://stackoverflow.com/questions/40032601/why-is-toctree-not-updating-with-rtd-theme).  Anyway, very very minor style bug - feel free to disregard, just thought I'd mention it.

**Comment by fediskhakov** [comment]
Thanks for noting this.
I believe that TOC is rebuilt every time, and the problem may have to do
with the web page not updating immediately.
