### ISSUE TITLE
Countable sets

### ISSUE THREAD

**Issue by eilui** [fediskhakov/OptimCourse#6]
In Lecture 3 (set theory) this claim is made:

![image](https://github.com/fediskhakov/OptimCourse/assets/142558976/58c6349d-a476-4b53-96d9-fb520d09c3da)

but I thought that the cardinality of A being the same as that of the natural numbers (aleph-0) would only apply to countably infinite sets (i.e. point 2), not to finite sets as well.

**Comment by eilui** [comment]
If that's correct, could be fixed simply by changing the equality to a weak inequality (|A| <= aleph-0), but an alternative fix could be better, up to you

**Comment by fediskhakov** [comment]
Indeed. I rearranged the definition to correspond aleph-0 to only the second clause.
